' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' Dieses Diagramm zeigt die Entity-Struktur für Supplements im Stil von TypeORM.
'
' Preview durch <Alt>d

@startuml Supplement

package typeorm {
  class "@Entity" as Entity
  hide Entity circle
  class "@Column" as Column
  hide Column circle
  class "@PrimaryColumn" as PrimaryColumn
  hide PrimaryColumn circle
  class "@OneToMany" as OneToMany
  hide OneToMany circle
  class "@OneToOne" as OneToOne
  hide OneToOne circle
  class "@JoinColumn" as JoinColumn
  hide JoinColumn circle
  class "@CreateDateColumn" as CreateDateColumn
  hide CreateDateColumn circle
  class "@UpdateDateColumn" as UpdateDateColumn
  hide UpdateDateColumn circle
}

package supplement.entity {
  class "type SupplementArt = 'PULVER' | 'TABLETTEN'" as SupplementArt
  hide SupplementArt circle

  class "type Rating = 1 | 2 | 3 | 4 | 5" as Rating
  hide Rating circle

  class Supplement <<entity>> <<@Entity>> {
    @PrimaryColumn() readonly id: number
    @Column() readonly namen: string
    @Column("simple-array") readonly menge: string[] ' z.B. "1000g,500g"
    @Column() readonly art: SupplementArt
    @Column() readonly rating: Rating
    @CreateDateColumn() readonly erzeugt: Date
    @UpdateDateColumn() readonly aktualisiert: Date
  }

  class Produktbild <<entity>> <<@Entity>> {
    @PrimaryColumn() readonly id: number
    @Column() readonly bezeichnung: string
    @Column() readonly path: string
    @ManyToOne(() => Supplement) supplement: Supplement
  }

  class Beschreibung <<entity>> <<@Entity>> {
    @PrimaryColumn() readonly id: number
    @Column() readonly info: string
    @Column() readonly vorteile: string
    @Column() readonly dosierempfehlung: string
    @OneToOne(() => Supplement) @JoinColumn() supplement: Supplement
  }

  Supplement *--> "*" Produktbild : @OneToMany() \nproduktbilder
  Supplement *--> "1" Beschreibung : @OneToOne() \nbeschreibung

  Supplement .right.> Entity
  Supplement .right.> SupplementArt
  Supplement .right.> Rating
}

hide empty members

@enduml
