name: CI/CD Pipeline

on:
  push:
    branches: ["main", "release/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    name: Lint (Prettier & ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npm run prettier:check
        # (Assumes "prettier:check": "prettier --check \"src/**/*.js\"" in package.json)

      - name: Run ESLint
        run: npm run lint
        # (Assumes "lint": "eslint \"src/**/*.js\"" in package.json)

  build-test:
    name: Build & Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        # (Assumes "build" script is defined in package.json)

      - name: Run tests
        run: npm test
        # (Assumes "test" script is defined in package.json)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    name: Deploy to Production
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: production      # creates GitHub environment “production”
      url: https://myapp.com
    concurrency:
      group: production-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="myorg/myapp:${{ github.sha }}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Notify deployment success
        run: echo "Deployed $IMAGE_NAME to production"

