name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [23.9.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean workspace
        run: |
          rm -rf src __tests__ node_modules dist \
            .extras/doc/api \
            .extras/doc/folien/folien.html \
            .extras/doc/projekthandbuch/html

      - name: Install dependencies
        run: npm ci --no-fund --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Run Tests
        run: npm run test:coverage
        # remove 'continue-on-error' if you want failures to fail the job
        continue-on-error: true

      - name: ESLint
        run: npm run eslint

      - name: Security Audit
        run: npm audit --omit=dev

      - name: Generate AsciiDoctor docs
        run: npm run asciidoctor

      - name: Generate reveal.js slides
        run: npm run revealjs

      - name: Generate TypeDoc API
        run: npm run typedoc

      - name: Upload Projekthandbuch
        uses: actions/upload-artifact@v3
        with:
          name: projekthandbuch
          path: .extras/doc/projekthandbuch/html/projekthandbuch.html

      - name: Upload TypeDoc API
        uses: actions/upload-artifact@v3
        with:
          name: typedoc
          path: .extras/doc/api/index.html

      - name: Zip distribution
        run: zip -r buch.zip dist

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v3
        with:
          name: buch
          path: buch.zip

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            supplement:${{ github.sha }}
            supplement:latest
